### ISSUE TITLE
Create a logger

### ISSUE THREAD

**Issue by Ermish** [ourjapanlife/findadoc-frontend#162]
# We need a proper logger.

### Acceptance Criteria

- [ ] Should provide essential logging methods `debug`, `info`, `warn`, `error`.
- [ ] Should `console.log` for local debugging. 
- [ ] For prod, temporarily `console.log` until we have a real logger. (It's better than not logging at all in case a user needs help.)

### TODO:
- [ ] In a separate issue, decide on a real client-side logger and integrate it for `prod` env mode.
